name: icem
channels:
  - conda-forge
dependencies:
  - python=3.11.4
  - numpy=1.25.0
  - jupyter
  - pandas=2.02
  - xarray=2023.5.0
  - rioxarray=0.14
  - scipy=1.10.1
  - matplotlib=3.7.1
  - rasterio=1.3.7
  - pip:
    - mplcyberpunk==0.7.0
    - rise==5.7.1
